# This workflow will build the project

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: unit-test CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    name: run-unit-test

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn gatling:test -Dgatling.simulationClass=simulations.TestChainingAPISimulations
    - name: archive artifacts
      uses: actions/upload-artifact@v3
      with:
        name: test-report
        path: |
          ./target/*index.html
